# ABOUTME: golangci-lint configuration for CI linting
# ABOUTME: Defines linters and rules for code quality checks
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - unused
    - gofmt
    - goimports
    - misspell
  disable:
    - errcheck
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 25

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Exclude linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - dupl
