# ABOUTME: Release workflow triggered by version tags
# ABOUTME: Builds multi-platform binaries and creates GitHub releases
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    name: Test Before Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopus-dev libopusfile-dev libflac-dev portaudio19-dev

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v -race ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m

  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    needs: test
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: darwin
            arch: amd64
            runner: macos-13
          - os: darwin
            arch: arm64
            runner: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopus-dev libopusfile-dev libflac-dev portaudio19-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'darwin'
      run: |
        brew install opus opusfile flac portaudio

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        mkdir -p dist

        # Player
        go build -ldflags "-X github.com/Resonate-Protocol/resonate-go/internal/version.Version=${{ steps.version.outputs.VERSION }}" \
          -o dist/resonate-player-${{ matrix.os }}-${{ matrix.arch }} .

        # Server
        go build -ldflags "-X github.com/Resonate-Protocol/resonate-go/internal/version.Version=${{ steps.version.outputs.VERSION }}" \
          -o dist/resonate-server-${{ matrix.os }}-${{ matrix.arch }} ./cmd/resonate-server

    - name: Create archives
      run: |
        cd dist
        for binary in *; do
          if [ -f "$binary" ]; then
            tar czf "${binary}.tar.gz" "$binary"
          fi
        done
        ls -lh *.tar.gz

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/*.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: binaries-*
        merge-multiple: true

    - name: List artifacts
      run: ls -lh artifacts/

    - name: Generate release notes
      id: release_notes
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 ${{ steps.version.outputs.VERSION }}^ 2>/dev/null || echo "")
        if [ -z "$PREV_TAG" ]; then
          echo "NOTES=Initial release" >> $GITHUB_OUTPUT
        else
          NOTES=$(git log --pretty=format:"- %s (%h)" ${PREV_TAG}..${{ steps.version.outputs.VERSION }})
          echo "NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          ## Resonate Protocol ${{ steps.version.outputs.VERSION }}

          ### Downloads

          **Player:**
          - Linux (amd64): `resonate-player-linux-amd64.tar.gz`
          - macOS (Intel): `resonate-player-darwin-amd64.tar.gz`
          - macOS (Apple Silicon): `resonate-player-darwin-arm64.tar.gz`

          **Server:**
          - Linux (amd64): `resonate-server-linux-amd64.tar.gz`
          - macOS (Intel): `resonate-server-darwin-amd64.tar.gz`
          - macOS (Apple Silicon): `resonate-server-darwin-arm64.tar.gz`

          ### Installation

          #### 1. Install Dependencies

          **macOS (via Homebrew):**
          ```bash
          brew install opus opusfile flac
          ```

          **Linux (Debian/Ubuntu):**
          ```bash
          sudo apt-get install libopus-dev libopusfile-dev libflac-dev
          ```

          **Linux (Fedora/RHEL):**
          ```bash
          sudo dnf install opus-devel opusfile-devel flac-devel
          ```

          **Or use the install script:**
          ```bash
          curl -fsSL https://raw.githubusercontent.com/harperreed/resonate-go/${{ steps.version.outputs.VERSION }}/install-deps.sh | bash
          ```

          #### 2. Download and Run

          ```bash
          # Extract
          tar xzf resonate-player-*.tar.gz

          # Make executable (if needed)
          chmod +x resonate-player-*

          # Run
          ./resonate-player-*
          ```

          ### Changes

          ${{ steps.release_notes.outputs.NOTES }}
        files: |
          artifacts/*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
